// <auto-generated />
using System;
using ETFTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ETFTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424203256_SplitUserSettingsFromProjectionSettings")]
    partial class SplitUserSettingsFromProjectionSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ETFTracker.Api.Models.AnnualTaxSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllowanceApplied")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("allowance_applied");

                    b.Property<decimal>("DeemedDisposalCredit")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("deemed_disposal_credit");

                    b.Property<int?>("HoldingId")
                        .HasColumnType("integer")
                        .HasColumnName("holding_id");

                    b.Property<decimal>("NetGain")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("net_gain");

                    b.Property<decimal>("PaidTaxAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("paid_tax_amount");

                    b.Property<DateTime>("RecalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recalculated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxDue")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("tax_due");

                    b.Property<decimal>("TaxRateUsed")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_rate_used");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_type");

                    b.Property<int>("TaxYear")
                        .HasColumnType("integer")
                        .HasColumnName("tax_year");

                    b.Property<decimal>("TaxableGain")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("taxable_gain");

                    b.Property<decimal>("TotalLosses")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_losses");

                    b.Property<decimal>("TotalProfits")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_profits");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId");

                    b.HasIndex("UserId");

                    b.ToTable("annual_tax_summary", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.AssetTypeDeemedDisposalDefault", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("asset_type");

                    b.Property<bool>("DeemedDisposalDue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deemed_disposal_due");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AssetType")
                        .IsUnique();

                    b.ToTable("asset_type_deemed_disposal_defaults", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("AverageCost")
                        .HasColumnType("numeric")
                        .HasColumnName("average_cost");

                    b.Property<string>("Broker")
                        .HasColumnType("text")
                        .HasColumnName("broker");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EtfName")
                        .HasColumnType("text")
                        .HasColumnName("etf_name");

                    b.Property<string>("PriceSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("price_source");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Ticker");

                    b.HasIndex("UserId", "Ticker")
                        .IsUnique();

                    b.ToTable("holdings", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.PriceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_date");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate");

                    b.HasIndex("Ticker");

                    b.HasIndex("Ticker", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("price_snapshots", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.ProfileShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GuestUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuestUserId");

                    b.HasIndex("OwnerId");

                    b.ToTable("ProfileShares");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.ProjectionSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualBuyIncreasePercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("annual_buy_increase_percent");

                    b.Property<decimal>("CgtPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("cgt_percent");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("InflationPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("inflation_percent");

                    b.Property<decimal>("MonthlyBuyAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monthly_buy_amount");

                    b.Property<int>("ProjectionYears")
                        .HasColumnType("integer")
                        .HasColumnName("projection_years");

                    b.Property<decimal?>("StartAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("start_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<decimal>("YearlyReturnPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("yearly_return_percent");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("projection_settings", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.ProjectionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualBuyIncreasePercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("annual_buy_increase_percent");

                    b.Property<decimal>("CgtPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("cgt_percent");

                    b.Property<string>("DataPointsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_points_json");

                    b.Property<decimal>("InflationPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("inflation_percent");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<decimal>("MonthlyBuyAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monthly_buy_amount");

                    b.Property<int>("ProjectionYears")
                        .HasColumnType("integer")
                        .HasColumnName("projection_years");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at");

                    b.Property<decimal?>("StartAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("start_amount");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("version_name");

                    b.Property<decimal>("YearlyReturnPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("yearly_return_percent");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("projection_versions", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.SellLotAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdjustedCostPerUnit")
                        .HasColumnType("numeric");

                    b.Property<int>("BuyTransactionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DeemedDisposalDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("DeemedDisposalPricePerUnit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OriginalCostPerUnit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProfitOnLot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantityConsumed")
                        .HasColumnType("numeric");

                    b.Property<int>("SellRecordId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuyTransactionId");

                    b.HasIndex("SellRecordId");

                    b.ToTable("SellLotAllocations");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.SellRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HoldingId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("SellDate")
                        .HasColumnType("date");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxAmountSaved")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxRateUsed")
                        .HasColumnType("numeric");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalProfit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId");

                    b.ToTable("SellRecords");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.TaxEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuyTransactionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostBasisPerUnit")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<int>("HoldingId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PricePerUnitAtEvent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantityAtEvent")
                        .HasColumnType("numeric");

                    b.Property<int?>("SellRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxRateUsed")
                        .HasColumnType("numeric");

                    b.Property<string>("TaxSubType")
                        .HasColumnType("text");

                    b.Property<decimal>("TaxableGain")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuyTransactionId");

                    b.HasIndex("HoldingId");

                    b.HasIndex("SellRecordId");

                    b.HasIndex("UserId");

                    b.ToTable("TaxEvents");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("DeemedDisposalDue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deemed_disposal_due");

                    b.Property<int>("HoldingId")
                        .HasColumnType("integer")
                        .HasColumnName("holding_id");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("purchase_price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId");

                    b.HasIndex("PurchaseDate");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("GitHubId")
                        .HasColumnType("text");

                    b.Property<string>("GitHubUsername")
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.UserGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GoalPointsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SourceVersionId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserGoals");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CgtPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(33m)
                        .HasColumnName("cgt_percent");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("DeemedDisposalEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deemed_disposal_enabled");

                    b.Property<decimal>("DeemedDisposalPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(41m)
                        .HasColumnName("deemed_disposal_percent");

                    b.Property<decimal>("ExitTaxPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(41m)
                        .HasColumnName("exit_tax_percent");

                    b.Property<bool>("IsIrishInvestor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_irish_investor");

                    b.Property<decimal>("SiaAnnualPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("sia_annual_percent");

                    b.Property<decimal>("TaxFreeAllowancePerYear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tax_free_allowance_per_year");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.AnnualTaxSummary", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.Holding", "Holding")
                        .WithMany()
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ETFTracker.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.AssetTypeDeemedDisposalDefault", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.Holding", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.User", "User")
                        .WithMany("Holdings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.ProfileShare", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.User", "GuestUser")
                        .WithMany("SharedWithMe")
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ETFTracker.Api.Models.User", "Owner")
                        .WithMany("SharedByMe")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuestUser");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.ProjectionSettings", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.User", "User")
                        .WithOne("ProjectionSettings")
                        .HasForeignKey("ETFTracker.Api.Models.ProjectionSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.ProjectionVersion", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.SellLotAllocation", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.Transaction", "BuyTransaction")
                        .WithMany()
                        .HasForeignKey("BuyTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ETFTracker.Api.Models.SellRecord", "SellRecord")
                        .WithMany("LotAllocations")
                        .HasForeignKey("SellRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyTransaction");

                    b.Navigation("SellRecord");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.SellRecord", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.Holding", "Holding")
                        .WithMany("SellRecords")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.TaxEvent", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.Transaction", "BuyTransaction")
                        .WithMany()
                        .HasForeignKey("BuyTransactionId");

                    b.HasOne("ETFTracker.Api.Models.Holding", "Holding")
                        .WithMany("TaxEvents")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ETFTracker.Api.Models.SellRecord", "SellRecord")
                        .WithMany()
                        .HasForeignKey("SellRecordId");

                    b.HasOne("ETFTracker.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyTransaction");

                    b.Navigation("Holding");

                    b.Navigation("SellRecord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.Transaction", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.Holding", "Holding")
                        .WithMany("Transactions")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.UserGoal", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.UserSettings", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("ETFTracker.Api.Models.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.Holding", b =>
                {
                    b.Navigation("SellRecords");

                    b.Navigation("TaxEvents");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.SellRecord", b =>
                {
                    b.Navigation("LotAllocations");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.User", b =>
                {
                    b.Navigation("Holdings");

                    b.Navigation("ProjectionSettings");

                    b.Navigation("SharedByMe");

                    b.Navigation("SharedWithMe");

                    b.Navigation("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
