// <auto-generated />
using System;
using ETFTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ETFTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419080412_AddDeemedDisposalPercent")]
    partial class AddDeemedDisposalPercent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ETFTracker.Api.Models.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageCost")
                        .HasColumnType("numeric")
                        .HasColumnName("average_cost");

                    b.Property<string>("Broker")
                        .HasColumnType("text")
                        .HasColumnName("broker");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EtfName")
                        .HasColumnType("text")
                        .HasColumnName("etf_name");

                    b.Property<string>("PriceSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("price_source");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Ticker");

                    b.HasIndex("UserId", "Ticker")
                        .IsUnique();

                    b.ToTable("holdings", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.PriceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_date");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate");

                    b.HasIndex("Ticker");

                    b.HasIndex("Ticker", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("price_snapshots", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.ProfileShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guest_email");

                    b.Property<int?>("GuestUserId")
                        .HasColumnType("integer")
                        .HasColumnName("guest_user_id");

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_read_only");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("GuestUserId");

                    b.HasIndex("OwnerId", "GuestEmail")
                        .IsUnique();

                    b.ToTable("profile_shares", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.ProjectionSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualBuyIncreasePercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("annual_buy_increase_percent");

                    b.Property<decimal>("CgtPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("cgt_percent");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("DeemedDisposalPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(41m)
                        .HasColumnName("deemed_disposal_percent");

                    b.Property<bool>("ExcludePreExistingFromTax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("exclude_pre_existing_from_tax");

                    b.Property<decimal>("ExitTaxPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("exit_tax_percent");

                    b.Property<decimal>("InflationPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("inflation_percent");

                    b.Property<bool>("IsIrishInvestor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_irish_investor");

                    b.Property<decimal>("MonthlyBuyAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monthly_buy_amount");

                    b.Property<int>("ProjectionYears")
                        .HasColumnType("integer")
                        .HasColumnName("projection_years");

                    b.Property<decimal>("SiaAnnualPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("sia_annual_percent");

                    b.Property<decimal?>("StartAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("start_amount");

                    b.Property<decimal>("TaxFreeAllowancePerYear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tax_free_allowance_per_year");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<decimal>("YearlyReturnPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("yearly_return_percent");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("projection_settings", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.ProjectionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualBuyIncreasePercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("annual_buy_increase_percent");

                    b.Property<decimal>("CgtPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("cgt_percent");

                    b.Property<string>("DataPointsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_points_json");

                    b.Property<bool>("ExcludePreExistingFromTax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("exclude_pre_existing_from_tax");

                    b.Property<decimal>("ExitTaxPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("exit_tax_percent");

                    b.Property<decimal>("InflationPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("inflation_percent");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<decimal>("MonthlyBuyAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monthly_buy_amount");

                    b.Property<int>("ProjectionYears")
                        .HasColumnType("integer")
                        .HasColumnName("projection_years");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at");

                    b.Property<decimal>("SiaAnnualPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("sia_annual_percent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("version_name");

                    b.Property<decimal>("YearlyReturnPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("yearly_return_percent");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("projection_versions", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.SellLotAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdjustedCostPerUnit")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("adjusted_cost_per_unit");

                    b.Property<int>("BuyTransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("buy_transaction_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DeemedDisposalDate")
                        .HasColumnType("date")
                        .HasColumnName("deemed_disposal_date");

                    b.Property<decimal?>("DeemedDisposalPricePerUnit")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("deemed_disposal_price_per_unit");

                    b.Property<decimal>("OriginalCostPerUnit")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("original_cost_per_unit");

                    b.Property<decimal>("ProfitOnLot")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("profit_on_lot");

                    b.Property<decimal>("QuantityConsumed")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("quantity_consumed");

                    b.Property<int>("SellRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("sell_record_id");

                    b.HasKey("Id");

                    b.HasIndex("BuyTransactionId");

                    b.HasIndex("SellRecordId");

                    b.ToTable("sell_lot_allocations", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.SellRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CgtPaid")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("cgt_paid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("HoldingId")
                        .HasColumnType("integer")
                        .HasColumnName("holding_id");

                    b.Property<bool>("IsIrishInvestor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_irish_investor");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("quantity");

                    b.Property<DateOnly>("SellDate")
                        .HasColumnType("date")
                        .HasColumnName("sell_date");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("sell_price");

                    b.Property<decimal>("TaxRateUsed")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_rate_used");

                    b.Property<decimal>("TotalProfit")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_profit");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId");

                    b.ToTable("sell_records", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.TaxEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuyTransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("buy_transaction_id");

                    b.Property<decimal>("CostBasisPerUnit")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("cost_basis_per_unit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<int>("HoldingId")
                        .HasColumnType("integer")
                        .HasColumnName("holding_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<decimal>("PricePerUnitAtEvent")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("price_per_unit_at_event");

                    b.Property<decimal>("QuantityAtEvent")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("quantity_at_event");

                    b.Property<int?>("SellRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("sell_record_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TaxRateUsed")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_rate_used");

                    b.Property<decimal>("TaxableGain")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("taxable_gain");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId");

                    b.HasIndex("SellRecordId");

                    b.HasIndex("UserId");

                    b.HasIndex("BuyTransactionId", "EventDate")
                        .IsUnique()
                        .HasFilter("buy_transaction_id IS NOT NULL");

                    b.ToTable("tax_events", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("HoldingId")
                        .HasColumnType("integer")
                        .HasColumnName("holding_id");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("purchase_price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId");

                    b.HasIndex("PurchaseDate");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("GitHubId")
                        .HasColumnType("text");

                    b.Property<string>("GitHubUsername")
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.UserGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GoalPointsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("goal_points_json");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at");

                    b.Property<int?>("SourceVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("source_version_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_goals", (string)null);
                });

            modelBuilder.Entity("ETFTracker.Api.Models.Holding", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.User", "User")
                        .WithMany("Holdings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.ProfileShare", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.User", "GuestUser")
                        .WithMany("SharedWithMe")
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ETFTracker.Api.Models.User", "Owner")
                        .WithMany("SharedByMe")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuestUser");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.ProjectionSettings", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.User", "User")
                        .WithOne("ProjectionSettings")
                        .HasForeignKey("ETFTracker.Api.Models.ProjectionSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.ProjectionVersion", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.SellLotAllocation", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.Transaction", "BuyTransaction")
                        .WithMany()
                        .HasForeignKey("BuyTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ETFTracker.Api.Models.SellRecord", "SellRecord")
                        .WithMany("LotAllocations")
                        .HasForeignKey("SellRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyTransaction");

                    b.Navigation("SellRecord");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.SellRecord", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.Holding", "Holding")
                        .WithMany("SellRecords")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.TaxEvent", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.Transaction", "BuyTransaction")
                        .WithMany()
                        .HasForeignKey("BuyTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ETFTracker.Api.Models.Holding", "Holding")
                        .WithMany("TaxEvents")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ETFTracker.Api.Models.SellRecord", "SellRecord")
                        .WithMany()
                        .HasForeignKey("SellRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ETFTracker.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyTransaction");

                    b.Navigation("Holding");

                    b.Navigation("SellRecord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.Transaction", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.Holding", "Holding")
                        .WithMany("Transactions")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.UserGoal", b =>
                {
                    b.HasOne("ETFTracker.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.Holding", b =>
                {
                    b.Navigation("SellRecords");

                    b.Navigation("TaxEvents");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.SellRecord", b =>
                {
                    b.Navigation("LotAllocations");
                });

            modelBuilder.Entity("ETFTracker.Api.Models.User", b =>
                {
                    b.Navigation("Holdings");

                    b.Navigation("ProjectionSettings");

                    b.Navigation("SharedByMe");

                    b.Navigation("SharedWithMe");
                });
#pragma warning restore 612, 618
        }
    }
}
