CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE TABLE price_snapshots (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        ticker text NOT NULL,
        price numeric NOT NULL,
        snapshot_date timestamp with time zone NOT NULL,
        source text,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_price_snapshots" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE TABLE users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        email text NOT NULL,
        first_name text,
        last_name text,
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE TABLE holdings (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        ticker text NOT NULL,
        etf_name text,
        quantity numeric NOT NULL,
        average_cost numeric NOT NULL,
        broker text,
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_holdings" PRIMARY KEY (id),
        CONSTRAINT "FK_holdings_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE TABLE projection_settings (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        yearly_return_percent numeric(5,2) NOT NULL,
        monthly_buy_amount numeric(12,2) NOT NULL,
        annual_buy_increase_percent numeric(5,2) NOT NULL,
        projection_years integer NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_projection_settings" PRIMARY KEY (id),
        CONSTRAINT "FK_projection_settings_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE TABLE transactions (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        holding_id integer NOT NULL,
        quantity numeric NOT NULL,
        purchase_price numeric NOT NULL,
        purchase_date date NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_transactions" PRIMARY KEY (id),
        CONSTRAINT "FK_transactions_holdings_holding_id" FOREIGN KEY (holding_id) REFERENCES holdings (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE INDEX "IX_holdings_ticker" ON holdings (ticker);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE UNIQUE INDEX "IX_holdings_user_id_ticker" ON holdings (user_id, ticker);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE INDEX "IX_price_snapshots_snapshot_date" ON price_snapshots (snapshot_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE INDEX "IX_price_snapshots_ticker" ON price_snapshots (ticker);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE UNIQUE INDEX "IX_price_snapshots_ticker_snapshot_date" ON price_snapshots (ticker, snapshot_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE UNIQUE INDEX "IX_projection_settings_user_id" ON projection_settings (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE INDEX "IX_transactions_holding_id" ON transactions (holding_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE INDEX "IX_transactions_purchase_date" ON transactions (purchase_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    CREATE UNIQUE INDEX "IX_users_email" ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401193155_AddProjectionSettings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260401193155_AddProjectionSettings', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401201157_AddInflationPercent') THEN
    ALTER TABLE projection_settings ADD inflation_percent numeric(5,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401201157_AddInflationPercent') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260401201157_AddInflationPercent', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402121722_AddPriceSourceToHoldings') THEN
    ALTER TABLE holdings ADD price_source character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402121722_AddPriceSourceToHoldings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260402121722_AddPriceSourceToHoldings', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402142416_AddTaxSettingsToProjections') THEN
    ALTER TABLE projection_settings ADD cgt_percent numeric(5,2) NOT NULL DEFAULT 38.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402142416_AddTaxSettingsToProjections') THEN
    ALTER TABLE projection_settings ADD exit_tax_percent numeric(5,2) NOT NULL DEFAULT 38.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402142416_AddTaxSettingsToProjections') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260402142416_AddTaxSettingsToProjections', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260403130000_AddExcludePreExistingFromTax') THEN
    ALTER TABLE projection_settings ADD exclude_pre_existing_from_tax boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260403130000_AddExcludePreExistingFromTax') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260403130000_AddExcludePreExistingFromTax', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404105223_AddOAuthFieldsToUser') THEN
    DROP INDEX "IX_users_email";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404105223_AddOAuthFieldsToUser') THEN
    ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404105223_AddOAuthFieldsToUser') THEN
    ALTER TABLE users ADD avatar_url text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404105223_AddOAuthFieldsToUser') THEN
    ALTER TABLE users ADD github_id text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404105223_AddOAuthFieldsToUser') THEN
    ALTER TABLE users ADD github_username text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404105223_AddOAuthFieldsToUser') THEN
    ALTER TABLE users ADD google_id text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404105223_AddOAuthFieldsToUser') THEN
    CREATE UNIQUE INDEX "IX_users_email" ON users (email) WHERE email IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404105223_AddOAuthFieldsToUser') THEN
    CREATE UNIQUE INDEX "IX_users_github_id" ON users (github_id) WHERE github_id IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404105223_AddOAuthFieldsToUser') THEN
    CREATE UNIQUE INDEX "IX_users_google_id" ON users (google_id) WHERE google_id IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404105223_AddOAuthFieldsToUser') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260404105223_AddOAuthFieldsToUser', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404113445_AddOAuthToUser') THEN
    DROP INDEX "IX_users_email";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404113445_AddOAuthToUser') THEN
    DROP INDEX "IX_users_github_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404113445_AddOAuthToUser') THEN
    DROP INDEX "IX_users_google_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404113445_AddOAuthToUser') THEN
    ALTER TABLE users RENAME COLUMN google_id TO "GoogleId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404113445_AddOAuthToUser') THEN
    ALTER TABLE users RENAME COLUMN github_username TO "GitHubUsername";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404113445_AddOAuthToUser') THEN
    ALTER TABLE users RENAME COLUMN github_id TO "GitHubId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404113445_AddOAuthToUser') THEN
    ALTER TABLE users RENAME COLUMN avatar_url TO "AvatarUrl";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404113445_AddOAuthToUser') THEN
    CREATE UNIQUE INDEX "IX_users_email" ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260404113445_AddOAuthToUser') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260404113445_AddOAuthToUser', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405090447_AddProjectionVersions') THEN
    CREATE TABLE projection_versions (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        version_number integer NOT NULL,
        saved_at timestamp with time zone NOT NULL,
        yearly_return_percent numeric(5,2) NOT NULL,
        monthly_buy_amount numeric(12,2) NOT NULL,
        annual_buy_increase_percent numeric(5,2) NOT NULL,
        projection_years integer NOT NULL,
        inflation_percent numeric(5,2) NOT NULL,
        cgt_percent numeric(5,2) NOT NULL,
        exit_tax_percent numeric(5,2) NOT NULL,
        exclude_pre_existing_from_tax boolean NOT NULL DEFAULT FALSE,
        data_points_json text NOT NULL,
        CONSTRAINT "PK_projection_versions" PRIMARY KEY (id),
        CONSTRAINT "FK_projection_versions_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405090447_AddProjectionVersions') THEN
    CREATE UNIQUE INDEX "IX_projection_versions_user_id_version_number" ON projection_versions (user_id, version_number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405090447_AddProjectionVersions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260405090447_AddProjectionVersions', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405094955_AddStartAmountToProjectionSettings') THEN
    ALTER TABLE projection_settings ADD start_amount numeric(15,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405094955_AddStartAmountToProjectionSettings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260405094955_AddStartAmountToProjectionSettings', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406140936_AddProfileSharing') THEN
    CREATE TABLE profile_shares (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        owner_id integer NOT NULL,
        guest_email character varying(256) NOT NULL,
        guest_user_id integer,
        is_read_only boolean NOT NULL DEFAULT TRUE,
        status integer NOT NULL DEFAULT 0,
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_profile_shares" PRIMARY KEY (id),
        CONSTRAINT "FK_profile_shares_users_guest_user_id" FOREIGN KEY (guest_user_id) REFERENCES users (id) ON DELETE SET NULL,
        CONSTRAINT "FK_profile_shares_users_owner_id" FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406140936_AddProfileSharing') THEN
    CREATE INDEX "IX_profile_shares_guest_user_id" ON profile_shares (guest_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406140936_AddProfileSharing') THEN
    CREATE UNIQUE INDEX "IX_profile_shares_owner_id_guest_email" ON profile_shares (owner_id, guest_email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406140936_AddProfileSharing') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260406140936_AddProfileSharing', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260408182857_AddUpdatedAtToPriceSnapshot') THEN
    ALTER TABLE price_snapshots ADD updated_at timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260408182857_AddUpdatedAtToPriceSnapshot') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260408182857_AddUpdatedAtToPriceSnapshot', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260408190000_AddVersionNameAndDefault') THEN
    DROP INDEX "IX_projection_versions_user_id_version_number";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260408190000_AddVersionNameAndDefault') THEN
    ALTER TABLE projection_versions DROP COLUMN version_number;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260408190000_AddVersionNameAndDefault') THEN
    ALTER TABLE projection_versions ADD version_name character varying(200) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260408190000_AddVersionNameAndDefault') THEN
    ALTER TABLE projection_versions ADD is_default boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260408190000_AddVersionNameAndDefault') THEN
    CREATE INDEX "IX_projection_versions_user_id" ON projection_versions (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260408190000_AddVersionNameAndDefault') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260408190000_AddVersionNameAndDefault', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260411090715_AddSiaAnnualPercent') THEN
    ALTER TABLE projection_versions ADD sia_annual_percent numeric(5,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260411090715_AddSiaAnnualPercent') THEN
    ALTER TABLE projection_settings ADD sia_annual_percent numeric(5,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260411090715_AddSiaAnnualPercent') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260411090715_AddSiaAnnualPercent', '10.0.5');
    END IF;
END $EF$;
COMMIT;

